name: app_detect
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  image_picker: ^0.8.4+4
  path_provider: ^2.0.7
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
